# -*- coding: utf-8 -*-
"""Quata Drug Notify.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oq3yQ-6e-lFbctcZKz1LTtbblec-Re4L
"""

!pip install openpyxl==3.0.10
import pandas as pd
import numpy as np
!pip install parinya
import parinya
import time
from parinya import LINE
#Import File Master
master_file = pd.ExcelFile('Master Quota Drug Remind.xlsx')
master = pd.read_excel(master_file, 'Master')
quota = pd.read_excel(master_file, 'Quota')
#Import File Purchase Requisition
total_pr = pd.read_excel('Data Total PR.XLSX')
#Select Column total_pr
total_pr = total_pr[['PR Material No','PR Material Desc','PR Qty']]
total_pr.columns = total_pr.columns.str.replace(' ','_')
total_pr
#Groupby
total_pr = total_pr.groupby(['PR_Material_No']).sum()
#Merge Table
total_pr = pd.merge(total_pr,master, left_on="PR_Material_No", right_on="MaterialNumber", how="left")
#Move Column
total_pr = total_pr[['MaterialNumber', 'MaterialDescription', 'MaterialGroup', 'PR_Qty','Weighted']]
#Calculate Total Qty
total_pr['Total_Purchase'] = (total_pr.PR_Qty*total_pr.Weighted)
#Summary Qty By MaterialGroup
total_pr = total_pr.groupby(['MaterialGroup']).sum()
# reset index
total_pr = total_pr.reset_index()
#Select Column Total Purchase
total_pr = total_pr[['MaterialGroup','Total_Purchase']]
#Merge Table with quota
total_pr = pd.merge(total_pr,quota, left_on="MaterialGroup", right_on="MaterialGroup", how="left")
total_pr = total_pr[['MaterialGroup', 'Quota', 'Total_Purchase']]
total_pr['%Purchase'] = (total_pr.Total_Purchase/total_pr.Quota)*100
line = LINE('5FdyAwX8ouUaL6EuRYSnpCHwOZwLvIh1O716YRYpVLq')
total_pr = total_pr.sort_values(by='%Purchase',axis=0,ascending=False)
total_pr = total_pr.reset_index(drop=True)
total_pr = total_pr.round({'Total_Purchase':2,'%Purchase':2})
for ind in total_pr.index:
    dummy = "Group : {} | Purchase = {}%".format(total_pr['MaterialGroup'][ind],total_pr['%Purchase'][ind])
    line.sendtext(dummy)
time.sleep(1)
