# -*- coding: utf-8 -*-
"""Usage MS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vhkfiLvMID0np_EJsMBUqP06yx0Brfor
"""

#Raw data usage ms.XLSX : Tcode ZMMR14
#Raw data stock.XLSX : Tcode ZMMR05
import pandas as pd
import numpy as np
import datetime
import time
from google.colab import files
#Process File Usage
df = pd.read_excel('Raw data usage ms.XLSX')
#Select Column df Relevant
df = df[['Material','Total Qty( 3 months )']]
#Gruop by Material
df = df.groupby('Material',as_index=False).sum()
df['AvgUsageRate'] = df['Total Qty( 3 months )']*-1/90
df = df[['Material','AvgUsageRate']]
#Process File Stock
Master = pd.read_excel('Raw data stock.XLSX')
Master = Master.drop_duplicates(subset=['Material'])
Master.reset_index(drop=True, inplace=True)
#Merge Master to df
df = df.merge(Master,on='Material',how='right')
#Select All Material Medical Supply
# df = df[df['Ext. Material Group']==1]
df = df[df['Plant-sp.matl status']!='ZZ']
df['max_day'] = 0
df['max_month'] = 0
# df = df[df['AvgUsageRate']>=0]
df['AvgUsageRate'] = df['AvgUsageRate'].fillna(0)
#Add Column Check No Plan
df['Check'] = np.where(df['AvgUsageRate']== 0, 'No Plan', '')
#Find & Replace Value
df['AvgUsageRate'] = df['AvgUsageRate'].replace(0, 0.01)
df['AvgUsageRate']=df['AvgUsageRate'].apply(lambda x:round(x,2)) #Round 2 Digits
#Final Column
df = df[['Material','AvgUsageRate','max_day','max_month','Check']]
#Replace Header Name
df.rename(columns = {'Check': ''}, inplace = True)    
# Export to Excel with Date Execute
# TodaysDate = time.strftime("%d-%m-%Y")
TodaysDate = time.strftime("%Y%m%d")
excelfilename = TodaysDate +"_Plan_PR.xlsx"
df.to_excel(excelfilename, sheet_name='sheet1', index=False)
# df.to_excel('Plan_PR.xlsx', encoding = 'utf-8-sig',index=False) 
files.download(excelfilename)